
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "app_main.h"
#include "uib_views.h"

/* event handler declarations */
void view2_listitem1_onitemselected(uib_view2_view_context*, Evas_Object*, void*);

uib_view_context* uib_view2_view_create(Evas_Object* parent, void* create_callback_param) {
	app_data *ad = (app_data*)evas_object_data_get(elm_object_top_widget_get(parent), "root");
	if (ad == NULL) {
		return NULL;
	}
	elm_win_indicator_mode_set(ad->win, ELM_WIN_INDICATOR_SHOW);
	uib_view2_view_context* vc = calloc(1, sizeof(uib_view2_view_context));
	vc->ad = ad;
	vc->parent = parent;
	vc->view_name = "view2";
	vc->box1= elm_box_add(parent);
	vc->root_container = vc->box1;
	if(vc->box1) {
		elm_box_homogeneous_set(vc->box1, EINA_FALSE);
		elm_box_horizontal_set(vc->box1, EINA_FALSE);
		elm_box_padding_set(vc->box1,0,0);
		evas_object_size_hint_align_set(vc->box1, -1.0, -1.0);
		evas_object_size_hint_weight_set(vc->box1, 1, 1);
		vc->list1= elm_list_add(vc->box1);
		if(vc->list1) {
			elm_list_select_mode_set(vc->list1, (Elm_Object_Select_Mode)0);
			elm_list_multi_select_set(vc->list1, EINA_FALSE);
			elm_list_horizontal_set(vc->list1, EINA_FALSE);
			elm_scroller_bounce_set(vc->list1, EINA_TRUE, EINA_TRUE);
			elm_scroller_policy_set(vc->list1, (Elm_Scroller_Policy)0, (Elm_Scroller_Policy)0);
			vc->listitem1 = elm_list_item_append(vc->list1, "List item", NULL, NULL, (Evas_Smart_Cb)view2_listitem1_onitemselected, vc);
			elm_list_item_selected_set(vc->listitem1, EINA_FALSE);
			vc->listitem2 = elm_list_item_append(vc->list1, "List item", NULL, NULL, NULL, NULL);
			elm_list_item_selected_set(vc->listitem2, EINA_FALSE);
			vc->listitem3 = elm_list_item_append(vc->list1, "List item", NULL, NULL, NULL, NULL);
			elm_list_item_selected_set(vc->listitem3, EINA_FALSE);
			vc->listitem4 = elm_list_item_append(vc->list1, "List item", NULL, NULL, NULL, NULL);
			elm_list_item_selected_set(vc->listitem4, EINA_FALSE);
			evas_object_size_hint_align_set(vc->list1, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->list1, 1, 1);
			elm_object_disabled_set(vc->list1, EINA_FALSE);
		elm_list_go(vc->list1);
			evas_object_show(vc->list1);		}
		elm_box_pack_end(vc->box1, vc->list1);
		evas_object_show(vc->box1);
	}
	//bind event handler

	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_view_destroy_callback, vc);
	uib_view_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	
	return (uib_view_context*)vc;
}
