
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "app_main.h"
#include "uib_views.h"

/* event handler declarations */

uib_view_context* uib_view1_view_create(Evas_Object* parent, void* create_callback_param) {
	app_data *ad = (app_data*)evas_object_data_get(elm_object_top_widget_get(parent), "root");
	if (ad == NULL) {
		return NULL;
	}
	elm_win_indicator_mode_set(ad->win, ELM_WIN_INDICATOR_SHOW);
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->ad = ad;
	vc->parent = parent;
	vc->view_name = "view1";
	vc->box1= elm_box_add(parent);
	vc->root_container = vc->box1;
	if(vc->box1) {
		elm_box_homogeneous_set(vc->box1, EINA_FALSE);
		elm_box_horizontal_set(vc->box1, EINA_FALSE);
		elm_box_padding_set(vc->box1,0,0);
		evas_object_size_hint_align_set(vc->box1, -1.0, -1.0);
		evas_object_size_hint_weight_set(vc->box1, 1, 1);
		vc->bg1 = elm_bg_add(vc->box1);
		if(vc->bg1) {
			evas_object_size_hint_align_set(vc->bg1, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bg1, 1, 1);			int hexValue = strtol("#c74242"+1, NULL, 16);
			int r = (hexValue&0xFF0000)>>16;
			int g = (hexValue&0xFF00)>>8;
			int b = (hexValue&0xFF);
			elm_bg_color_set(vc->bg1, r, g, b);
			evas_object_show(vc->bg1);
		}
		elm_box_pack_end(vc->box1, vc->bg1);
		evas_object_show(vc->box1);
	}
	//bind event handler

	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_view_destroy_callback, vc);
	uib_view_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	
	return (uib_view_context*)vc;
}
