
/*
* TODO : exceptional codegen for common view source
* View
*/

#ifndef UIB_VIEW2_VIEW_H_
#define UIB_VIEW2_VIEW_H_


/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

//#include <Elementary.h>
#include <app_main.h>
/**
* view context definitions
*/
		

typedef struct _uib_view2_view_context {

	/* parent evas_object which was parameter of create function */
	Evas_Object *parent;
	/* root container UI Component of this view */
	Evas_Object* root_container;
	/* view class name */
	const char *view_name;
	/* app data */
	app_data *ad;
	/* control context to control this view */
	struct _uib_view2_control_context *cc;

	/* UI Components in this view */
	Evas_Object *box1;
	Evas_Object *list1;
	Elm_Object_Item *listitem1;
	Elm_Object_Item *listitem2;
	Elm_Object_Item *listitem3;
	Elm_Object_Item *listitem4;
} uib_view2_view_context;


	
/**
* @brief	Create a new view then return view context of that view.
* 			You can delete view using evas_object_del(vc->evas_object) like other EFL evas objects.
*/	


uib_view_context *uib_view2_view_create(Evas_Object *parent, void *create_callback_param);
uib_view_context *uib_view2_view_destroy(Evas_Object *parent, void *create_callback_param);

#endif /* UIB_VIEW2_VIEW_H_ */
