
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be	auto-generated each and every time you save your project.
* Do not hand edit this file.
********************************************************************************/
	#include "uib_views.h"

